[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
[build]
  command = "yarn build && yarn export"
  publish = "out"

[context.production]
  environment = { WORDPRESS_GRAPHQL_ENDPOINT = "https://hillandvalleynews.com/graphql"}